repos:
- repo: https://github.com/norwoodj/helm-docs
  rev: v1.6.0
  hooks:
  - id: helm-docs
    args:
    - --chart-search-root=chart
    - --template-files=./_templates.gotmpl
    - --template-files=README.md.gotmpl
