services:
  openvpn-client:
    image: ghcr.io/dj-mcculloch/openvpn-client:latest
    container_name: openvpn-client
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      ALLOWED_SUBNETS: 192.168.10.0/24
      AUTH_SECRET: /config/credentials.txt
    volumes:
      - ./local:/config
    restart: unless-stopped
