{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) (or .Values.httpProxy.enabled .Values.socksProxy.enabled) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openvpn-client.authSecretName" . }}
  labels:
    {{- include "openvpn-client.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.auth.proxyUsername | b64enc | quote }}
  password: {{ .Values.auth.proxyPassword | b64enc | quote }}
{{- end -}}
