apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openvpn-client.configSecretName" . }}
  labels:
    {{- include "openvpn-client.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $fileName, $fileContent := $.Values.configFiles.files }}
  {{ $fileName }}: |-
    {{- $fileContent | b64enc | nindent 4 }}
  {{- end }}
