name: Build and Push to GHCR

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: tags
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/dj-mcculloch/openvpn-client
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}

    - name: Set build arguments
      id: build-args
      run: |
        ref=${{ github.ref }}
        vpatch=${ref##refs/*/}
        patch=${vpatch#v}
        echo "date=$(date --utc --iso-8601=seconds)" >> $GITHUB_OUTPUT
        echo "version=$patch" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: "{{defaultContext}}:build"
        platforms: linux/amd64,linux/arm64
        build-args: |
          BUILD_DATE=${{ steps.build-args.outputs.date }}
          IMAGE_VERSION=${{ steps.build-args.outputs.version }}
        tags: ${{ steps.tags.outputs.tags }}
        push: true
