name: Publish

on:
  push:
    tags:
      - v*

env:
  IMAGE_NAME: openvpn-client

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        id: qemu
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Log in to registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: ${{ steps.qemu.outputs.platforms }}
          tags: |
            ghcr.io/wfg/openvpn-client:${{ steps.get_version.outputs.VERSION }}
            ghcr.io/wfg/openvpn-client:latest
          push: true
