name: Mark issues as stale

on:
  schedule:
    - cron: '0 3 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@v4
        with:
          stale-issue-label: no-issue-activity
          stale-pr-label: no-pr-activity
          days-before-stale: 30
          days-before-close: -1
          exempt-assignees: wfg
          any-of-labels: needs-more-info
